name: 'Install Google Fonts'
description: 'Install fonts from Google Fonts in GitHub Actions'
author: jim60105
branding:
  icon: type
  color: blue
inputs:
  fonts:
    description: 'Font families to install (comma-separated or newline-separated). Example: "Roboto,Noto Sans TC,Noto Color Emoji"'
    required: true
  weights:
    description: 'Font weights to install (comma-separated: 100,300,400,500,700,900)'
    required: false
    default: '400,700'
runs:
  using: "composite"
  steps:
    - run: |
        if [ ! -d "$HOME/.fonts" ]; then
          mkdir -p "$HOME/.fonts"
          echo "create ~/.fonts/"
        fi
      shell: bash
    
    - run: |
        echo "::group::Download and install fonts"
        ${{ github.action_path }}/download_fonts.sh \
          -w "${{ inputs.weights }}" \
          "${{ inputs.fonts }}"
        echo "::endgroup::"
      shell: bash
    
    - run: |
        echo "::group::Update font cache"
        sudo fc-cache -fv
        echo "::endgroup::"
      shell: bash
    
    - run: |
        echo "::group::Cleanup"
        rm -rf fonts_temp/ 2>/dev/null || true
        rm -f *.css 2>/dev/null || true
        echo "::endgroup::"
      shell: bash
